# Netlify Configuration
[build]
  publish = "."
  
# Form handling
[[forms]]
  name = "contact"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirects
[[redirects]]
  from = "https://zeroxlabs.netlify.app/*"
  to = "https://zeroxlabs.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://zeroxlabs.com/*"
  to = "https://zeroxlabs.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.zeroxlabs.com/*"
  to = "https://zeroxlabs.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/contact-success"
  to = "/thank-you.html"
  status = 200

# 404 handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
